export const actionTypes = {
    USER_GET_REQUEST: "USER_GET_REQUEST",
    USER_GET_SUCCESS: "USER_GET_SUCCESS",
    USER_GET_FAILURE: "USER_GET_FAILURE",
    USER_GET_RESET: "USER_GET_RESET",

    USER_POST_REQUEST: "USER_POST_REQUEST",
    USER_POST_SUCCESS: "USER_POST_SUCCESS",
    USER_POST_FAILURE: "USER_POST_FAILURE",
    USER_POST_RESET: "USER_POST_RESET",

    USER_PUT_REQUEST: "USER_PUT_REQUEST",
    USER_PUT_SUCCESS: "USER_PUT_SUCCESS",
    USER_PUT_FAILURE: "USER_PUT_FAILURE",
    USER_PUT_RESET: "USER_PUT_RESET",

    USER_DELETE_REQUEST: "USER_DELETE_REQUEST",
    USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
    USER_DELETE_FAILURE: "USER_DELETE_FAILURE",
    USER_DELETE_RESET: "USER_DELETE_RESET",
}